spring:
  application:
    name: order-server
  config:
    import: "optional:configserver:"
    activate:
      on-profile:
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      hub-server:
        failure-rate-threshold: 50          # 회로 차단 기준
        minimum-number-of-calls: 5          # 최소 통계 횟수
        sliding-window-size: 10             # 최근 호출 기준 개수
        wait-duration-in-open-state: 10s    # 차단 후 복구 시도까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3  # 복구 시도 시 허용되는 호출 수
      delivery-server:
        failure-rate-threshold: 50          # 회로 차단 기준
        minimum-number-of-calls: 5          # 최소 통계 횟수
        sliding-window-size: 10             # 최근 호출 기준 개수
        wait-duration-in-open-state: 10s    # 차단 후 복구 시도까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3  # 복구 시도 시 허용되는 호출 수
      message-server:
        failure-rate-threshold: 50          # 회로 차단 기준
        minimum-number-of-calls: 5          # 최소 통계 횟수
        sliding-window-size: 10             # 최근 호출 기준 개수
        wait-duration-in-open-state: 10s    # 차단 후 복구 시도까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3  # 복구 시도 시 허용되는 호출 수
  retry:
    instances:
      hub-server:
        max-attempts: 3
        wait-duration: 500ms
      delivery-server:
        max-attempts: 3
        wait-duration: 500ms
      message-server:
        max-attempts: 3
        wait-duration: 500ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    sampling:
      probability: 1.0 # 1.0은 100% 기록 (운영 환경에서는 부하를 위해 0.1(10%) 등으로 낮춤)
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"